
/** ----------------------------------------------------------------------------------------------------
* 
*	This code was automatically generated by the LeanFT Application Model code generator.
*
*	Changes to this file may cause incorrect behavior and will be lost 
*	when the code is regenerated.
*
*   ----------------------------------------------------------------------------------------------------
*/
package ObjectRepository;

import com.hp.lft.sdk.*;

// This class is automatically generated by the LeanFT Application Model code generator - version 14.52
public class Login_Repo extends AppModelBase {	
	public Login_Repo(TestObject contextTestObject) throws GeneralLeanFtException
	{
		setName("Login_Repo");
				rebuildDescriptions();
	}	
}
